name: Build and deploy AWS ECR

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and Push to ECR
      if: github.ref == 'refs/heads/main'
      env:
        ECR_REGISTRY: 244530008913.dkr.ecr.eu-west-1.amazonaws.com
        ECR_REPOSITORY: kandidat2010ecr-sensur
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
     
  deploy-with-terraform:
    needs: [build-and-deploy]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: eu-west-1

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        working-directory: ./infra

        env:
          TF_VAR_ecr_uri: 244530008913.dkr.ecr.eu-west-1.amazonaws.com/kandidat2010ecr:latest
          TF_VAR_apprunner_name: kandidat2010
          TF_VAR_apprunner_role: kandidat2010role
          TF_VAR_policy_name: kandidat2010policy
          TF_VAR_cloudwatch_namespace: 2010namespace
          TF_VAR_cloudwatch_step: 10s
          TF_VAR_dashboard_name: 2010dashboard








